/* Generated By:JavaCC: Do not edit this line. AnalizadorEjemploConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorEjemploConstants {

  /** End of File. */
  int EOF = 0;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"A\"",
  };

}
